### ISSUE TITLE
Absolute numbering not working correctly

### ISSUE THREAD

**Issue by robleedes** [psouza4/mediacentermaster#1711]
Double digits numbers are not recognized, in order to process files use has to add a "0"

Sometimes the Airing schedule change does not stick, after clicking "Save"

Intermittent refresh issue, and sometimes the program locks up.

See: "Forum Bug Report Topic [(here)](http://forums.mediacentermaster.com/viewtopic.php?f=6&t=11146)

**Comment by psouza4** [comment]
First, double digits are not allowed as absolute numbering AAA format.  They never have and there's no unambiguous proposal to change that.  As a result, this issue is being dismissed.

Second, airing schedule saving issues should be reported in their own, separate issue.  However, it should probably be evaluated in depth first as my testing has not been able to reproduce the issue.  Specific data on how to reproduce an issue must be provided.

Third, program instability/freezing/etc. should be troubleshooted in great length at the forums.  It's almost always an issue where the program is waiting for Windows to handshake with a disk or network device (filesystem I/O).

**Comment by psouza4** [comment]
As a follow-up to this, it's not unreasonable to have AA anymore since they're no longer ambiguous with show-specific settings.  I was wrong about that, and opened and resolved the enhancement request to bring that functionality to the application.  See issue #1718.
