### ISSUE TITLE
Force by thetvdb id

### ISSUE THREAD

**Issue by Kedryn** [psouza4/mediacentermaster#1745]
I have a strange result when i have to resort to "Force by thetvdb.com id"
If i put an ID, i often get more than one result, and that's strange when i put only one ID.

Today i was trying to scrape "The Family".
If i do a fetch, i get many results, but the one i need isnt among them.
Then i do a "Force" using 295516 , but i get same results (maybe 6-7 other older series), but not the one with that ID. Why? I thought "force" means that MMC will pick that one and not look for others...

**Comment by Happy2Play** [comment]
Didn't have any issue force fetching by thetvdb id 295516.
``12:22 PM :: [12:22:45.922] Fetching URL (GET):  http://thetvdb.com/api/767CE15749DAFFA2/series/295516/all/en.xml
12:22 PM :: [12:22:46.042] DEBUG:  Saved to cache: E:\1 TV\The Family
12:22 PM :: [12:22:46.062] Fetching URL (GET):  http://thetvdb.com/api/767CE15749DAFFA2/series/295516/en.xml
12:22 PM :: [12:22:46.156] DEBUG:  Saved to cache: E:\1 TV\The Family
12:22 PM :: thetvdb.com  Updated base metadata for this show
12:22 PM :: [12:22:46.158] DEBUG:  thetvdb.com  Looking for artwork to download for this show
12:22 PM :: thetvdb.com  Fetching show poster...``


There is minor error somewhere since the media list shows <error> during the force fetch by in the end after fetch is complete the proper name is displayed "The Family (2016)".

**Comment by Kedryn** [comment]
found out that was renamed to "The Family (2016)"
I'll try again and update here

**Comment by psouza4** [comment]
Unverified report.
