### ISSUE TITLE
Language Encoding, wrong encoding in thetvdb

### ISSUE THREAD

**Issue by Totto16** [psouza4/mediacentermaster#1862]
Since the update of the API from thetvdb.com the episodes have wromg encoding in languages like german, the characters who uses 2 Bytes in UTF-8 are shown as two ??. Before that update it was fine, this doesn't seem to happen to movies.
![duplicates](https://user-images.githubusercontent.com/32566573/63599140-421bf800-c5c1-11e9-8479-1308a5a8a018.png)

**Comment by psouza4** [comment]
You might be using v3 of the fetcher plugin and should be using v2.  I can't tell, because you did not submit your required support information here or at the forums.

Please observe this rule for reporting bugs:
_All bug report issues must be discussed at the community forums first for verification. If an issue is confirmed, it should be posted here as a Bug Report or Source Change depending the type of issue._
